- category: mandatory
  customVariables: []
  description: Replace the Spring Cloud Config Client artifact with Quarkus 'quarkus-spring-cloud-config-client'
    extension
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/target=quarkus
  links:
  - title: Quarkus - Reading properties from Spring Cloud Config server
    url: https://quarkus.io/guides/spring-cloud-config-client
  - title: Spring Cloud Config
    url: https://cloud.spring.io/spring-cloud-config/reference/html/
  message: "Replace the Spring Cloud Config Client artifact with Quarkus `quarkus-spring-cloud-config-client`
    extension\n\n Add Quarkus dependency `io.quarkus:quarkus-spring-cloud-config-client`.\n
    \n A change may also be required to the code and configuration."
  ruleID: springboot-cloud-config-client-to-quarkus-00000
  when:
    or:
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-config-client
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-config-client
