- category: potential
  customVariables: []
  description: 'Bootable JAR Maven Plugin: rename extraServerContent configuration
    element'
  effort: 1
  labels:
  - konveyor.io/source=eapxp
  - konveyor.io/target=eapxp3+
  - konveyor.io/target=eapxp
  - JBossEAP
  - EAPXP
  links:
  - title: 'JBoss EAP XP upgrade and migration guide: Bootable JAR application migration'
    url: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/jboss_eap_xp_upgrade_and_migration_guide/index#microprofile-application-migration-bootable-jar_default
  message: If you migrate your application to JBoss EAP XP 3.0 (or later), and want
    to ensure its Maven building, running or testing works as expected, rename the
    configuration element `extraServerContent` to `extraServerContentDirs`.
  ruleID: eapxp_bootable_jar_maven_plugin_configuration_changes-1
  when:
    builtin.xml:
      filepaths:
      - pom.xml
      namespaces:
        m: http://maven.apache.org/POM/4.0.0
      xpath: //m:plugin[m:groupId/text() = 'org.wildfly.plugins' and m:artifactId/text()
        = 'wildfly-jar-maven-plugin']/m:configuration/m:extraServerContent
