name: E2E Hub Koncur

on:
  push:
    branches:
    - main
    - 'release-*'
  pull_request:
    branches:
    - main
    - 'release-*'
  workflow_dispatch:

jobs:
  e2e-hub-koncur:
    if: github.repository == 'konveyor/rulesets'
    uses: konveyor/ci/.github/workflows/e2e-hub-koncur.yaml@main
