name: Trigger seed in tackle2-hub

on:
  push:
    branches:
      - main
      - 'release-*'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      rules_changed: ${{ steps.filter.outputs.rules_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rules_changed:
              - 'stable/**/*.yaml'
              - '!**/*.test.yaml'

  trigger-seed:
    needs: filter
    if: needs.filter.outputs.rules_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ vars.KONVEYOR_BOT_ID }}
          application_private_key: ${{ secrets.KONVEYOR_BOT_KEY }}
          # Permission needed to send repository_dispatch
          permissions: "contents:write"
          revoke_token: true
      - name: Dispatch event to create seed PR
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          repository: "konveyor/tackle2-seed"
          event-type: trigger-seed
          client-payload: '{ "branch": "${{ github.ref_name }}" }'
